### ISSUE TITLE
ImportError with Python 3.4

### ISSUE THREAD

**Issue by folz** [synapsepay/SynapsePayRest-Python#1]
```
➜  syntest  mkvirtualenv -a ~/Projects/syntest -p $(which python3) syntest
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in syntest/bin/python3
Also creating executable in syntest/bin/python
Installing setuptools, pip...done.
Setting project for syntest to /home/user/Projects/syntest
(syntest)➜  syntest  python --version
Python 3.4.3
```

```
(syntest)➜  syntest  pip install synapse_pay_rest
Collecting synapse-pay-rest
  Using cached synapse_pay_rest-0.0.26.tar.gz
Collecting requests (from synapse-pay-rest)
  Using cached requests-2.8.1-py2.py3-none-any.whl
Installing collected packages: requests, synapse-pay-rest
  Running setup.py install for synapse-pay-rest
Successfully installed requests-2.8.1 synapse-pay-rest-0.0.26
```

```
(syntest)➜  syntest  python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from synapse_pay_rest import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/syntest/lib/python3.4/site-packages/synapse_pay_rest/__init__.py", line 1, in <module>
    from synapse_pay_rest.client import Client
  File "/home/user/.virtualenvs/syntest/lib/python3.4/site-packages/synapse_pay_rest/client.py", line 2, in <module>
    from http_client import *
ImportError: No module named 'http_client'
>>> 
```

**Comment by sankaet** [comment]
@folz [this](https://github.com/synapsepay/SynapsePayRest-Python/pull/2) should've resolved the mentioned issue. So I will close this for now
